In [1]:
import pandas as pd
import numpy as np
from pandas.io.json import json_normalize
import requests
import pprint
import json

In [2]:
import time

## 위도, 경도 -> 주소 변환

In [3]:
def lat_lon_to_addr(lon,lat):
    url = 'https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={longitude}&y={latitude}'.format(longitude=lon,latitude=lat)
    headers = {"Authorization": "KakaoAK " + 'KEY'}
    result = json.loads(str(requests.get(url, headers=headers).text))
    match_first = result['documents'][0]['address_name']
    return str(match_first)

In [4]:
# test
lat_lon_to_addr(129.101613720014,35.2569765925029)

'부산광역시 금정구 구서동'

In [16]:
df = pd.read_excel("vdsid 별 위도 경도.xlsx")

In [18]:
df.head(3)

          vdsId          경도         위도
0  0010VDE00100  129.101614  35.256977
1  0010VDE00200  129.105973  35.265211
2  0010VDE00500  129.100226  35.287171

In [19]:
newdf = df[['경도','위도']]
newdf.head(3)

           경도         위도
0  129.101614  35.256977
1  129.105973  35.265211
2  129.100226  35.287171

In [20]:
xcode = newdf['경도'].tolist()
ycode = newdf['위도'].tolist()

In [21]:
len(xcode)

1120

In [22]:
binlist = []

for i in range(len(xcode)):
  print(i,'번째',lat_lon_to_addr(xcode[i], ycode[i]))
  binlist.append(lat_lon_to_addr(xcode[i], ycode[i]))

print('----finished----')

0 번째 부산광역시 금정구 구서동
1 번째 부산광역시 금정구 선동
2 번째 부산광역시 금정구 노포동
3 번째 부산광역시 금정구 노포동
4 번째 경상남도 양산시 북부동
5 번째 경상남도 양산시 상북면 소토리
6 번째 울산광역시 울주군 삼동면 조일리
7 번째 울산광역시 울주군 언양읍 직동리
8 번째 울산광역시 울주군 두서면 활천리
9 번째 경상북도 경주시 율동
10 번째 경상북도 경주시 건천읍 송선리
11 번째 경상북도 영천시 북안면 반정리
12 번째 경상북도 영천시 금호읍 구암리
13 번째 경상북도 경산시 하양읍 환상리
14 번째 대구광역시 동구 부동
15 번째 대구광역시 동구 도동
16 번째 대구광역시 북구 조야동
17 번째 대구광역시 북구 금호동
18 번째 경상북도 칠곡군 지천면 연화리
19 번째 경상북도 칠곡군 왜관읍 삼청리
20 번째 경상북도 구미시 오태동
21 번째 경상북도 구미시 광평동
22 번째 경상북도 김천시 아포읍 봉산리
23 번째 경상북도 김천시 남면 초곡리
24 번째 경상북도 김천시 삼락동
25 번째 경상북도 김천시 봉산면 광천리
26 번째 충청북도 영동군 황간면 마산리
27 번째 충청북도 영동군 용산면 구촌리
28 번째 충청북도 옥천군 동이면 조령리
29 번째 충청북도 옥천군 옥천읍 옥각리
30 번째 대전광역시 동구 비룡동
31 번째 대전광역시 대덕구 송촌동
32 번째 대전광역시 대덕구 와동
33 번째 대전광역시 대덕구 목상동
34 번째 충청북도 청주시 서원구 남이면 부용외천리
35 번째 충청북도 청주시 서원구 남이면 척산리
36 번째 충청북도 청주시 흥덕구 석곡동
37 번째 충청북도 청주시 흥덕구 강내면 학천리
38 번째 충청북도 청주시 흥덕구 옥산면 오산리
39 번째 충청북도 청주시 흥덕구 옥산면 사정리
40 번째 충청남도 천안시 동남구 목천읍 응원리
41 번째 충청남도 천안시 동남구 삼룡동
42 번째 충청남도 천안시 동남구 신부동
43 번째 충청남도 천안시 서북구 입장면 용정리
44 번째 경기도 평택시 용이동
45 번째 경기도 안성시 원곡면 외가천리
46 번째 경기도 오산시 오산동
47 번째 경기도 화성시 방교동
48 번째 경기도 용인시 기흥구 고매동
49 번째 경기도 용인시 기흥구 고매동
50 번째 경기도 용인시 기흥구 상갈동
51 번째 경기도 용인시 기흥구 신갈동
52 번째 경기도 성남시 분당구 삼평동
53 번째 경기도 성남시 수정구 금토동
54 번째 경기도 성남시 수정구 금토동
55 번째 서울특별시 서초구 양재동
56 번째 부산광역시 금정구 구서동
57 번째 부산광역시 금정구 선동
58 번째 부산광역시 금정구 노포동
59 번째 부산광역시 금정구 노포동
60 번째 경상남도 양산시 북부동
61 번째 경상남도 양산시 상북면 소토리
62 번째 울산광역시 울주군 삼동면 조일리
63 번째 울산광역시 울주군 언양읍 직동리
64 번째 울산광역시 울주군 두서면 활천리
65 번째 경상북도 경주시 율동
66 번째 경상북도 경주시 건천읍 송선리
67 번째 경상북도 영천시 북안면 반정리
68 번째 경상북도 영천시 금호읍 구암리
69 번째 경상북도 경산시 하양읍 환상리
70 번째 대구광역시 동구 부동
71 번째 대구광역시 동구 도동
72 번째 대구광역시 북구 조야동
73 번째 대구광역시 북구 금호동
74 번째 경상북도 칠곡군 지천면 연화리
75 번째 경상북도 칠곡군 왜관읍 삼청리
76 번째 경상북도 구미시 오태동
77 번째 경상북도 구미시 광평동
78 번째 경상북도 김천시 아포읍 봉산리
79 번째 경상북도 김천시 남면 초곡리
80 번째 경상북도 김천시 삼락동
81 번째 경상북도 김천시 봉산면 광천리
82 번째 충청북도 영동군 황간면 마산리
83 번째 충청북도 영동군 용산면 구촌리
84 번째 충청북도 옥천군 동이면 조령리
85 번째 충청북도 옥천군 옥천읍 옥각리
86 번째 대전광역시 동구 비룡동
87 번째 대전광역시 대덕구 송촌동
88 번째 대전광역시 대덕구 와동
89 번째 대전광역시 대덕구 목상동
90 번째 충청북도 청주시 서원구 남이면 부용외천리
91 번째 충청북도 청주시 서원구 남이면 석실리
92 번째 충청북도 청주시 흥덕구 석곡동
93 번째 충청북도 청주시 흥덕구 강내면 학천리
94 번째 충청북도 청주시 흥덕구 옥산면 오산리
95 번째 충청북도 청주시 흥덕구 옥산면 사정리
96 번째 충청남도 천안시 동남구 목천읍 응원리
97 번째 충청남도 천안시 동남구 삼룡동
98 번째 충청남도 천안시 동남구 신부동
99 번째 충청남도 천안시 서북구 입장면 용정리
100 번째 경기도 평택시 용이동
101 번째 경기도 안성시 원곡면 외가천리
102 번째 경기도 오산시 오산동
103 번째 경기도 화성시 방교동
104 번째 경기도 용인시 기흥구 고매동
105 번째 경기도 용인시 기흥구 고매동
106 번째 경기도 용인시 기흥구 상갈동
107 번째 경기도 용인시 기흥구 신갈동
108 번째 경기도 성남시 분당구 삼평동
109 번째 경기도 성남시 수정구 금토동
110 번째 경기도 성남시 수정구 금토동
111 번째 서울특별시 서초구 양재동
112 번째 전라남도 순천시 서면 죽평리
113 번째 전라남도 순천시 서면 압곡리
114 번째 전라남도 순천시 서면 구상리
115 번째 전라남도 광양시 광양읍 용강리
116 번째 전라남도 광양시 중군동
117 번째 전라남도 광양시 옥곡면 신금리
118 번째 전라남도 광양시 진월면 선소리
119 번째 경상남도 하동군 금남면 덕천리
120 번째 경상남도 하동군 진교면 고이리
121 번째 경상남도 사천시 곤양면 대진리
122 번째 경상남도 사천시 축동면 구호리
123 번째 경상남도 진주시 정촌면 화개리
124 번째 경상남도 진주시 호탄동
125 번째 경상남도 진주시 문산읍 상문리
126 번째 경상남도 진주시 진성면 동산리
127 번째 경상남도 진주시 지수면 승산리
128 번째 경상남도 함안군 군북면 장지리
129 번째 경상남도 함안군 군북면 유현리
130 번째 경상남도 함안군 가야읍 묘사리
131 번째 경상남도 함안군 칠원읍 오곡리
132 번째 경상남도 함안군 칠원읍 오곡리
133 번째 경상남도 함안군 칠원읍 무기리
134 번째 경상남도 창원시 의창구 북면 외감리
135 번째 경상남도 창원시 의창구 동읍 용강리
136 번째 경상남도 창원시 의창구 동읍 송정리
137 번째 경상남도 김해시 진영읍 하계리
138 번째 경상남도 김해시 진례면 청천리
139 번째 경상남도 김해시 주촌면 양동리
140 번째 경상남도 김해시 주촌면 양동리
141 번째 경상남도 김해시 흥동
142 번째 경상남도 김해시 삼정동
143 번째 경상남도 김해시 불암동
144 번째 부산광역시 강서구 대저1동
145 번째 부산광역시 강서구 대저1동
146 번째 전라남도 순천시 서면 죽평리
147 번째 전라남도 순천시 서면 압곡리
148 번째 전라남도 순천시 서면 구상리
149 번째 전라남도 광양시 광양읍 용강리
150 번째 전라남도 광양시 중군동
151 번째 전라남도 광양시 옥곡면 신금리
152 번째 전라남도 광양시 진월면 선소리
153 번째 경상남도 하동군 금남면 덕천리
154 번째 경상남도 하동군 진교면 고이리
155 번째 경상남도 사천시 곤양면 대진리
156 번째 경상남도 사천시 축동면 구호리
157 번째 경상남도 진주시 정촌면 화개리
158 번째 경상남도 진주시 호탄동
159 번째 경상남도 진주시 문산읍 상문리
160 번째 경상남도 진주시 진성면 동산리
161 번째 경상남도 진주시 지수면 승산리
162 번째 경상남도 함안군 군북면 장지리
163 번째 경상남도 함안군 군북면 유현리
164 번째 경상남도 함안군 가야읍 묘사리
165 번째 경상남도 함안군 칠원읍 오곡리
166 번째 경상남도 함안군 칠원읍 오곡리
167 번째 경상남도 함안군 칠원읍 무기리
168 번째 경상남도 창원시 의창구 북면 외감리
169 번째 경상남도 창원시 의창구 동읍 용강리
170 번째 경상남도 창원시 의창구 동읍 송정리
171 번째 경상남도 김해시 진례면 청천리
172 번째 경상남도 김해시 진례면 청천리
173 번째 경상남도 김해시 주촌면 양동리
174 번째 경상남도 김해시 주촌면 양동리
175 번째 경상남도 김해시 흥동
176 번째 경상남도 김해시 삼정동
177 번째 경상남도 김해시 불암동
178 번째 부산광역시 강서구 대저1동
179 번째 부산광역시 강서구 대저1동
180 번째 전라남도 영암군 학산면 은곡리
181 번째 전라남도 영암군 학산면 은곡리
182 번째 전라남도 영암군 서호면 청용리
183 번째 전라남도 영암군 학산면 금계리
184 번째 전라남도 강진군 성전면 영풍리
185 번째 전라남도 장흥군 부산면 부춘리
186 번째 전라남도 보성군 미력면 화방리
187 번째 전라남도 보성군 벌교읍 마동리
188 번째 전라남도 보성군 벌교읍 영등리
189 번째 전라남도 순천시 별량면 덕정리
190 번째 전라남도 순천시 인월동
191 번째 전라남도 순천시 해룡면 도롱리
192 번째 전라남도 영암군 학산면 은곡리
193 번째 전라남도 영암군 학산면 은곡리
194 번째 전라남도 영암군 서호면 청용리
195 번째 전라남도 영암군 학산면 금계리
196 번째 전라남도 강진군 성전면 영풍리
197 번째 전라남도 장흥군 부산면 부춘리
198 번째 전라남도 보성군 미력면 화방리
199 번째 전라남도 보성군 벌교읍 마동리
200 번째 전라남도 보성군 벌교읍 영등리
201 번째 전라남도 순천시 별량면 덕정리
202 번째 전라남도 순천시 인월동
203 번째 전라남도 순천시 해룡면 도롱리
204 번째 전라남도 담양군 고서면 주산리
205 번째 전라남도 담양군 봉산면 유산리
206 번째 전라남도 담양군 무정면 영천리
207 번째 전라북도 순창군 순창읍 가남리
208 번째 전라북도 남원시 대산면 대곡리
209 번째 전라북도 남원시 월락동
210 번째 전라북도 남원시 산동면 대기리
211 번째 전라북도 남원시 아영면 봉대리
212 번째 경상남도 함양군 함양읍 대덕리
213 번째 경상남도 함양군 함양읍 백천리
214 번째 경상남도 함양군 함양읍 백천리
215 번째 경상남도 거창군 거창읍 대평리
216 번째 경상남도 거창군 가조면 도리
217 번째 경상남도 합천군 야로면 청계리
218 번째 경상북도 고령군 대가야읍 외리
219 번째 경상북도 고령군 성산면 고탄리
220 번째 대구광역시 달성군 논공읍 삼리리
221 번째 전라남도 담양군 고서면 주산리
222 번째 전라남도 담양군 봉산면 유산리
223 번째 전라남도 담양군 무정면 영천리
224 번째 전라북도 순창군 순창읍 가남리
225 번째 전라북도 남원시 대산면 대곡리
226 번째 전라북도 남원시 월락동
227 번째 전라북도 남원시 산동면 대기리
228 번째 전라북도 남원시 아영면 봉대리
229 번째 경상남도 함양군 함양읍 대덕리
230 번째 경상남도 함양군 함양읍 백천리
231 번째 경상남도 함양군 지곡면 공배리
232 번째 경상남도 거창군 거창읍 대평리
233 번째 경상남도 거창군 가조면 도리
234 번째 경상남도 합천군 야로면 청계리
235 번째 경상북도 고령군 대가야읍 외리
236 번째 경상북도 고령군 성산면 고탄리
237 번째 대구광역시 달성군 논공읍 삼리리
238 번째 전라남도 무안군 망운면 피서리
239 번째 전라남도 무안군 현경면 평산리
240 번째 전라남도 함평군 엄다면 성천리
241 번째 전라남도 함평군 학교면 마산리
242 번째 전라남도 나주시 문평면 송산리
243 번째 전라남도 나주시 노안면 계림리
244 번째 광주광역시 광산구 용곡동
245 번째 광주광역시 광산구 지죽동
246 번째 전라남도 무안군 망운면 피서리
247 번째 전라남도 무안군 현경면 평산리
248 번째 전라남도 함평군 엄다면 성천리
249 번째 전라남도 함평군 학교면 마산리
250 번째 전라남도 나주시 문평면 송산리
251 번째 전라남도 나주시 노안면 계림리
252 번째 광주광역시 광산구 용곡동
253 번째 광주광역시 광산구 지죽동
254 번째 전라북도 고창군 고수면 남산리
255 번째 전라북도 고창군 고수면 상평리
256 번째 전라남도 장성군 서삼면 송현리
257 번째 전라남도 장성군 장성읍 유탕리
258 번째 광주광역시 북구 용강동
259 번째 전라남도 담양군 창평면 유곡리
260 번째 전라북도 고창군 고수면 남산리
261 번째 전라북도 고창군 고수면 상평리
262 번째 전라남도 장성군 서삼면 송현리
263 번째 전라남도 장성군 장성읍 유탕리
264 번째 광주광역시 북구 용강동
265 번째 전라남도 담양군 창평면 유곡리
266 번째 전라남도 무안군 삼향읍 맥포리
267 번째 전라남도 무안군 일로읍 지장리
268 번째 전라남도 무안군 몽탄면 양장리
269 번째 전라남도 무안군 무안읍 용월리
270 번째 전라남도 함평군 함평읍 자풍리
271 번째 전라남도 함평군 손불면 죽암리
272 번째 전라북도 고창군 대산면 춘산리
273 번째 전라북도 고창군 고수면 예지리
274 번째 전라북도 고창군 고창읍 신월리
275 번째 전라북도 고창군 흥덕면 오호리
276 번째 전라북도 부안군 줄포면 대동리
277 번째 전라북도 부안군 동진면 하장리
278 번째 전라북도 김제시 만경읍 장산리
279 번째 전라북도 군산시 대야면 죽산리
280 번째 전라북도 군산시 나포면 서포리
281 번째 충청남도 서천군 기산면 내동리
282 번째 충청남도 서천군 종천면 종천리
283 번째 충청남도 보령시 주산면 증산리
284 번째 충청남도 보령시 웅천읍 죽청리
285 번째 충청남도 보령시 내항동
286 번째 충청남도 보령시 천북면 신덕리
287 번째 충청남도 홍성군 갈산면 행산리
288 번째 충청남도 서산시 해미면 오학리
289 번째 충청남도 서산시 운산면 갈산리
290 번째 충청남도 당진시 사기소동
291 번째 충청남도 당진시 송악읍 반촌리
292 번째 충청남도 당진시 송악읍 복운리
293 번째 경기도 평택시 포승읍 석정리
294 번째 경기도 평택시 청북읍 고잔리
295 번째 경기도 화성시 팔탄면 덕천리
296 번째 경기도 화성시 비봉면 구포리
297 번째 경기도 화성시 매송면 송라리
298 번째 경기도 안산시 상록구 팔곡일동
299 번째 경기도 시흥시 조남동
300 번째 경기도 안양시 만안구 박달동
301 번째 경기도 안양시 만안구 박달동
302 번째 경기도 광명시 일직동
303 번째 전라남도 무안군 삼향읍 맥포리
304 번째 전라남도 무안군 일로읍 지장리
305 번째 전라남도 무안군 몽탄면 양장리
306 번째 전라남도 무안군 무안읍 용월리
307 번째 전라남도 함평군 함평읍 자풍리
308 번째 전라남도 함평군 손불면 죽암리
309 번째 전라북도 고창군 대산면 춘산리
310 번째 전라북도 고창군 고수면 예지리
311 번째 전라북도 고창군 고창읍 신월리
312 번째 전라북도 고창군 흥덕면 오호리
313 번째 전라북도 부안군 줄포면 대동리
314 번째 전라북도 부안군 동진면 하장리
315 번째 전라북도 김제시 만경읍 장산리
316 번째 전라북도 군산시 대야면 죽산리
317 번째 전라북도 군산시 나포면 서포리
318 번째 충청남도 서천군 기산면 내동리
319 번째 충청남도 서천군 종천면 종천리
320 번째 충청남도 보령시 주산면 증산리
321 번째 충청남도 보령시 웅천읍 죽청리
322 번째 충청남도 보령시 내항동
323 번째 충청남도 보령시 천북면 신덕리
324 번째 충청남도 홍성군 갈산면 행산리
325 번째 충청남도 서산시 해미면 오학리
326 번째 충청남도 서산시 운산면 갈산리
327 번째 충청남도 당진시 사기소동
328 번째 충청남도 당진시 송악읍 반촌리
329 번째 충청남도 당진시 송악읍 복운리
330 번째 경기도 평택시 포승읍 석정리
331 번째 경기도 평택시 청북읍 고잔리
332 번째 경기도 화성시 팔탄면 덕천리
333 번째 경기도 화성시 비봉면 구포리
334 번째 경기도 화성시 매송면 송라리
335 번째 경기도 안산시 상록구 팔곡일동
336 번째 경기도 시흥시 조남동
337 번째 경기도 안양시 만안구 박달동
338 번째 경기도 안양시 만안구 박달동
339 번째 경기도 광명시 일직동
340 번째 울산광역시 울주군 언양읍 어음리
341 번째 울산광역시 울주군 언양읍 어음리
342 번째 경기도 평택시 오성면 양교리
343 번째 경기도 평택시 청북읍 백봉리
344 번째 경기도 평택시 청북읍 율북리
345 번째 경기도 화성시 양감면 용소리
346 번째 경기도 화성시 정남면 귀래리
347 번째 경기도 평택시 오성면 양교리
348 번째 경기도 평택시 청북읍 백봉리
349 번째 경기도 평택시 청북읍 율북리
350 번째 경기도 화성시 양감면 용소리
351 번째 경기도 화성시 정남면 귀래리
352 번째 대구광역시 동구 도동
353 번째 경상북도 영천시 청통면 죽정리
354 번째 경상북도 영천시 화산면 암기리
355 번째 경상북도 영천시 화남면 신호리
356 번째 경상북도 영천시 임고면 삼매리
357 번째 경상북도 포항시 북구 기계면 내단리
358 번째 대구광역시 동구 도동
359 번째 경상북도 영천시 청통면 죽정리
360 번째 경상북도 영천시 화산면 암기리
361 번째 경상북도 영천시 화남면 신호리
362 번째 경상북도 영천시 임고면 삼매리
363 번째 경상북도 포항시 북구 기계면 내단리
364 번째 전라북도 완주군 삼례읍 석전리
365 번째 전라북도 완주군 봉동읍 구만리
366 번째 전라북도 완주군 용진읍 상삼리
367 번째 전라북도 완주군 소양면 황운리
368 번째 전라북도 진안군 진안읍 구룡리
369 번째 전라북도 완주군 삼례읍 석전리
370 번째 전라북도 완주군 봉동읍 구만리
371 번째 전라북도 완주군 용진읍 상삼리
372 번째 전라북도 완주군 소양면 황운리
373 번째 전라북도 진안군 진안읍 구룡리
374 번째 전라남도 순천시 서면 동산리
375 번째 전라남도 순천시 승주읍 봉덕리
376 번째 전라남도 곡성군 목사동면 신기리
377 번째 전라남도 곡성군 석곡면 석곡리
378 번째 전라남도 곡성군 삼기면 의암리
379 번째 전라남도 곡성군 오산면 연화리
380 번째 전라남도 담양군 대덕면 매산리
381 번째 전라남도 담양군 고서면 산덕리
382 번째 전라남도 담양군 고서면 보촌리
383 번째 광주광역시 북구 문흥동
384 번째 광주광역시 북구 우산동
385 번째 광주광역시 북구 용봉동
386 번째 광주광역시 북구 연제동
387 번째 광주광역시 광산구 신창동
388 번째 광주광역시 광산구 수완동
389 번째 전라남도 장성군 남면 삼태리
390 번째 전라남도 장성군 남면 분향리
391 번째 전라남도 장성군 남면 녹진리
392 번째 전라남도 장성군 장성읍 수산리
393 번째 전라남도 장성군 장성읍 야은리
394 번째 전라남도 장성군 북이면 원덕리
395 번째 전라북도 정읍시 입암면 대흥리
396 번째 전라북도 정읍시 농소동
397 번째 전라북도 정읍시 태인면 증산리
398 번째 전라북도 김제시 금산면 용산리
399 번째 전라북도 김제시 금구면 용지리
400 번째 전라북도 완주군 이서면 갈산리
401 번째 전라북도 전주시 덕진구 용정동
402 번째 전라북도 익산시 왕궁면 온수리
403 번째 전라북도 익산시 왕궁면 구덕리
404 번째 전라북도 완주군 봉동읍 제내리
405 번째 전라남도 순천시 서면 동산리
406 번째 전라남도 순천시 승주읍 봉덕리
407 번째 전라남도 곡성군 목사동면 신기리
408 번째 전라남도 곡성군 석곡면 석곡리
409 번째 전라남도 곡성군 삼기면 의암리
410 번째 전라남도 곡성군 오산면 연화리
411 번째 전라남도 담양군 대덕면 매산리
412 번째 전라남도 담양군 고서면 산덕리
413 번째 전라남도 담양군 고서면 보촌리
414 번째 광주광역시 북구 문흥동
415 번째 광주광역시 북구 우산동
416 번째 광주광역시 북구 용봉동
417 번째 광주광역시 북구 연제동
418 번째 광주광역시 광산구 신창동
419 번째 광주광역시 광산구 수완동
420 번째 전라남도 장성군 남면 삼태리
421 번째 전라남도 장성군 남면 분향리
422 번째 전라남도 장성군 남면 녹진리
423 번째 전라남도 장성군 장성읍 수산리
424 번째 전라남도 장성군 장성읍 야은리
425 번째 전라남도 장성군 북이면 원덕리
426 번째 전라북도 정읍시 입암면 대흥리
427 번째 전라북도 정읍시 농소동
428 번째 전라북도 정읍시 태인면 증산리
429 번째 전라북도 김제시 금산면 용산리
430 번째 전라북도 김제시 금구면 용지리
431 번째 전라북도 완주군 이서면 갈산리
432 번째 전라북도 전주시 덕진구 용정동
433 번째 전라북도 익산시 왕궁면 온수리
434 번째 전라북도 익산시 왕궁면 구덕리
435 번째 전라북도 완주군 봉동읍 제내리
436 번째 전라남도 순천시 해룡면 복성리
437 번째 전라남도 순천시 서면 구상리
438 번째 전라남도 순천시 황전면 선변리
439 번째 전라남도 구례군 용방면 중방리
440 번째 전라북도 남원시 송동면 신평리
441 번째 전라북도 남원시 대산면 대곡리
442 번째 전라북도 남원시 대산면 운교리
443 번째 전라북도 임실군 오수면 대명리
444 번째 전라북도 임실군 성수면 도인리
445 번째 전라북도 전주시 완산구 색장동
446 번째 전라북도 전주시 덕진구 금상동
447 번째 전라남도 순천시 해룡면 복성리
448 번째 전라남도 순천시 서면 구상리
449 번째 전라남도 순천시 황전면 선변리
450 번째 전라남도 구례군 용방면 중방리
451 번째 전라북도 남원시 송동면 신평리
452 번째 전라북도 남원시 대산면 대곡리
453 번째 전라북도 남원시 대산면 운교리
454 번째 전라북도 임실군 오수면 대명리
455 번째 전라북도 임실군 성수면 도인리
456 번째 전라북도 전주시 덕진구 우아동1가
457 번째 전라북도 전주시 덕진구 금상동
458 번째 경기도 구리시 토평동
459 번째 서울특별시 중랑구 신내동
460 번째 경기도 남양주시 별내동
461 번째 경기도 의정부시 산곡동
462 번째 경기도 의정부시 민락동
463 번째 경기도 포천시 소흘읍 무봉리
464 번째 경기도 포천시 소흘읍 초가팔리
465 번째 경기도 포천시 가산면 마산리
466 번째 경기도 포천시 군내면 구읍리
467 번째 경기도 구리시 토평동
468 번째 경기도 구리시 갈매동
469 번째 경기도 남양주시 별내동
470 번째 경기도 의정부시 산곡동
471 번째 경기도 의정부시 민락동
472 번째 경기도 포천시 소흘읍 무봉리
473 번째 경기도 포천시 소흘읍 초가팔리
474 번째 경기도 포천시 가산면 마산리
475 번째 경기도 포천시 군내면 구읍리
476 번째 충청북도 청주시 서원구 남이면 척산리
477 번째 충청북도 청주시 상당구 가덕면 삼항리
478 번째 충청북도 보은군 회인면 건천리
479 번째 충청북도 보은군 보은읍 금굴리
480 번째 충청북도 보은군 장안면 봉비리
481 번째 경상북도 상주시 화서면 상곡리
482 번째 경상북도 상주시 지천동
483 번째 경상북도 상주시 낙동면 구잠리
484 번째 경상북도 의성군 단밀면 생송리
485 번째 경상북도 의성군 안계면 시안리
486 번째 경상북도 의성군 단촌면 세촌리
487 번째 경상북도 의성군 단촌면 하화리
488 번째 경상북도 안동시 길안면 만음리
489 번째 경상북도 청송군 파천면 중평리
490 번째 경상북도 청송군 진보면 괴정리
491 번째 충청북도 청주시 서원구 남이면 척산리
492 번째 충청북도 청주시 상당구 가덕면 삼항리
493 번째 충청북도 보은군 회인면 건천리
494 번째 충청북도 보은군 보은읍 금굴리
495 번째 충청북도 보은군 장안면 봉비리
496 번째 경상북도 상주시 화남면 평온리
497 번째 경상북도 상주시 화서면 상곡리
498 번째 경상북도 상주시 지천동
499 번째 경상북도 상주시 낙동면 구잠리
500 번째 경상북도 의성군 단밀면 생송리
501 번째 경상북도 의성군 안계면 시안리
502 번째 경상북도 의성군 단촌면 세촌리
503 번째 경상북도 의성군 단촌면 하화리
504 번째 경상북도 안동시 길안면 만음리
505 번째 경상북도 청송군 파천면 중평리
506 번째 경상북도 청송군 진보면 괴정리
507 번째 충청남도 당진시 사기소동
508 번째 충청남도 당진시 면천면 삼웅리
509 번째 충청남도 예산군 고덕면 상장리
510 번째 충청남도 예산군 오가면 신석리
511 번째 충청남도 예산군 신양면 대덕리
512 번째 충청남도 공주시 유구읍 유구리
513 번째 충청남도 공주시 사곡면 호계리
514 번째 충청남도 공주시 우성면 방문리
515 번째 충청남도 공주시 월미동
516 번째 충청남도 공주시 우성면 목천리
517 번째 세종특별자치시 장군면 하봉리
518 번째 대전광역시 유성구 안산동
519 번째 충청남도 당진시 사기소동
520 번째 충청남도 당진시 면천면 삼웅리
521 번째 충청남도 예산군 고덕면 상장리
522 번째 충청남도 예산군 오가면 신석리
523 번째 충청남도 예산군 신양면 대덕리
524 번째 충청남도 공주시 유구읍 유구리
525 번째 충청남도 공주시 사곡면 호계리
526 번째 충청남도 공주시 우성면 방문리
527 번째 충청남도 공주시 월미동
528 번째 충청남도 공주시 우성면 목천리
529 번째 세종특별자치시 장군면 하봉리
530 번째 대전광역시 유성구 안산동
531 번째 경상남도 통영시 용남면 동달리
532 번째 경상남도 통영시 광도면 죽림리
533 번째 경상남도 고성군 거류면 송산리
534 번째 경상남도 고성군 마암면 두호리
535 번째 경상남도 고성군 영오면 오서리
536 번째 경상남도 진주시 정촌면 화개리
537 번째 경상남도 진주시 판문동
538 번째 경상남도 산청군 단성면 사월리
539 번째 경상남도 산청군 금서면 특리
540 번째 경상남도 함양군 수동면 화산리
541 번째 경상남도 함양군 지곡면 공배리
542 번째 경상남도 함양군 지곡면 마산리
543 번째 경상남도 함양군 서상면 금당리
544 번째 전라북도 장수군 장계면 금덕리
545 번째 전라북도 무주군 안성면 죽천리
546 번째 전라북도 무주군 무주읍 용포리
547 번째 충청남도 금산군 군북면 호티리
548 번째 충청남도 금산군 추부면 요광리
549 번째 대전광역시 동구 구도동
550 번째 대전광역시 동구 대성동
551 번째 대전광역시 동구 삼정동
552 번째 경상남도 통영시 용남면 동달리
553 번째 경상남도 통영시 광도면 죽림리
554 번째 경상남도 고성군 거류면 송산리
555 번째 경상남도 고성군 마암면 두호리
556 번째 경상남도 고성군 영오면 오서리
557 번째 경상남도 진주시 정촌면 화개리
558 번째 경상남도 진주시 판문동
559 번째 경상남도 산청군 단성면 사월리
560 번째 경상남도 산청군 금서면 특리
561 번째 경상남도 함양군 수동면 화산리
562 번째 경상남도 함양군 지곡면 공배리
563 번째 경상남도 함양군 지곡면 마산리
564 번째 경상남도 함양군 서상면 금당리
565 번째 전라북도 장수군 장계면 금덕리
566 번째 전라북도 무주군 안성면 죽천리
567 번째 전라북도 무주군 무주읍 용포리
568 번째 충청남도 금산군 군북면 호티리
569 번째 충청남도 금산군 추부면 요광리
570 번째 대전광역시 동구 구도동
571 번째 대전광역시 동구 대성동
572 번째 대전광역시 동구 삼정동
573 번째 충청북도 청주시 흥덕구 석곡동
574 번째 충청북도 청주시 흥덕구 외북동
575 번째 충청북도 청주시 청원구 오창읍 상평리
576 번째 충청북도 청주시 청원구 오창읍 학소리
577 번째 충청북도 청주시 청원구 오창읍 여천리
578 번째 충청북도 진천군 진천읍 가산리
579 번째 충청북도 음성군 대소면 삼호리
580 번째 충청북도 음성군 대소면 오류리
581 번째 충청북도 음성군 삼성면 양덕리
582 번째 경기도 안성시 죽산면 매산리
583 번째 경기도 이천시 모가면 신갈리
584 번째 경기도 이천시 호법면 안평리
585 번째 경기도 이천시 마장면 표교리
586 번째 경기도 이천시 마장면 장암리
587 번째 경기도 이천시 신둔면 용면리
588 번째 경기도 광주시 곤지암읍 삼리
589 번째 경기도 광주시 초월읍 신월리
590 번째 경기도 광주시 남한산성면 상번천리
591 번째 경기도 하남시 상산곡동
592 번째 경기도 하남시 천현동
593 번째 경기도 하남시 천현동
594 번째 충청북도 청주시 흥덕구 석곡동
595 번째 충청북도 청주시 흥덕구 외북동
596 번째 충청북도 청주시 청원구 오창읍 상평리
597 번째 충청북도 청주시 청원구 오창읍 학소리
598 번째 충청북도 청주시 청원구 오창읍 여천리
599 번째 충청북도 진천군 진천읍 가산리
600 번째 충청북도 음성군 대소면 삼호리
601 번째 충청북도 음성군 대소면 오류리
602 번째 충청북도 음성군 삼성면 양덕리
603 번째 경기도 안성시 죽산면 매산리
604 번째 경기도 이천시 모가면 신갈리
605 번째 경기도 이천시 호법면 안평리
606 번째 경기도 이천시 마장면 표교리
607 번째 경기도 이천시 신둔면 용면리
608 번째 경기도 광주시 곤지암읍 삼리
609 번째 경기도 광주시 초월읍 신월리
610 번째 경기도 광주시 남한산성면 상번천리
611 번째 경기도 하남시 상산곡동
612 번째 경기도 하남시 천현동
613 번째 경기도 하남시 천현동
614 번째 경기도 이천시 신둔면 고척리
615 번째 경기도 이천시 신둔면 용면리
616 번째 경기도 광주시 곤지암읍 삼리
617 번째 경기도 광주시 초월읍 선동리
618 번째 경기도 광주시 초월읍 지월리
619 번째 경기도 광주시 남한산성면 상번천리
620 번째 경기도 이천시 신둔면 고척리
621 번째 경기도 광주시 곤지암읍 삼리
622 번째 경기도 광주시 초월읍 선동리
623 번째 경기도 광주시 초월읍 지월리
624 번째 경기도 광주시 남한산성면 상번천리
625 번째 경기도 평택시 청북읍 고잔리
626 번째 경기도 평택시 청북읍 고렴리
627 번째 경기도 평택시 청북읍 토진리
628 번째 경기도 평택시 고덕면 방축리
629 번째 경기도 안성시 원곡면 반제리
630 번째 경기도 안성시 미양면 구수리
631 번째 충청북도 진천군 이월면 내촌리
632 번째 충청북도 음성군 대소면 미곡리
633 번째 충청북도 음성군 금왕읍 삼봉리
634 번째 충청북도 음성군 금왕읍 육령리
635 번째 충청북도 충주시 신니면 문락리
636 번째 충청북도 충주시 노은면 문성리
637 번째 충청북도 충주시 노은면 수룡리
638 번째 충청북도 충주시 산척면 영덕리
639 번째 경기도 평택시 청북읍 고잔리
640 번째 경기도 평택시 청북읍 고렴리
641 번째 경기도 평택시 오성면 양교리
642 번째 경기도 평택시 고덕면 방축리
643 번째 경기도 안성시 원곡면 반제리
644 번째 경기도 안성시 미양면 구수리
645 번째 충청북도 진천군 이월면 내촌리
646 번째 충청북도 음성군 대소면 미곡리
647 번째 충청북도 음성군 금왕읍 삼봉리
648 번째 충청북도 음성군 금왕읍 육령리
649 번째 충청북도 충주시 신니면 문락리
650 번째 충청북도 충주시 노은면 문성리
651 번째 충청북도 충주시 노은면 수룡리
652 번째 충청북도 충주시 산척면 영덕리
653 번째 경상남도 창원시 마산회원구 내서읍 호계리
654 번째 경상남도 함안군 칠원읍 오곡리
655 번째 경상남도 함안군 칠서면 청계리
656 번째 경상남도 창녕군 남지읍 마산리
657 번째 경상남도 창녕군 계성면 봉산리
658 번째 경상남도 창녕군 대지면 효정리
659 번째 대구광역시 달성군 현풍읍 지리
660 번째 경상북도 고령군 성산면 대흥리
661 번째 경상북도 성주군 용암면 본리리
662 번째 경상북도 성주군 대가면 용흥리
663 번째 경상북도 김천시 남면 부상리
664 번째 경상북도 김천시 아포읍 송천리
665 번째 경상북도 구미시 선산읍 봉곡리
666 번째 경상북도 상주시 낙동면 내곡리
667 번째 경상북도 상주시 병성동
668 번째 경상북도 상주시 공검면 역곡리
669 번째 경상북도 상주시 함창읍 나한리
670 번째 경상북도 문경시 마성면 남호리
671 번째 충청북도 괴산군 연풍면 행촌리
672 번째 충청북도 괴산군 장연면 조곡리
673 번째 충청북도 충주시 대소원면 완오리
674 번째 충청북도 충주시 중앙탑면 하구암리
675 번째 충청북도 충주시 노은면 신효리
676 번째 충청북도 충주시 노은면 문성리
677 번째 충청북도 음성군 감곡면 상우리
678 번째 경기도 여주시 가남읍 본두리
679 번째 경기도 여주시 세종대왕면 오계리
680 번째 경기도 여주시 세종대왕면 번도리
681 번째 경기도 여주시 흥천면 문장리
682 번째 경기도 양평군 강상면 병산리
683 번째 경상남도 창원시 마산회원구 내서읍 호계리
684 번째 경상남도 함안군 칠원읍 오곡리
685 번째 경상남도 함안군 칠서면 청계리
686 번째 경상남도 창녕군 남지읍 마산리
687 번째 경상남도 창녕군 계성면 봉산리
688 번째 경상남도 창녕군 대지면 효정리
689 번째 대구광역시 달성군 현풍읍 지리
690 번째 경상북도 고령군 성산면 대흥리
691 번째 경상북도 성주군 용암면 본리리
692 번째 경상북도 성주군 대가면 용흥리
693 번째 경상북도 김천시 남면 부상리
694 번째 경상북도 김천시 아포읍 송천리
695 번째 경상북도 구미시 선산읍 봉곡리
696 번째 경상북도 상주시 낙동면 내곡리
697 번째 경상북도 상주시 병성동
698 번째 경상북도 상주시 공검면 역곡리
699 번째 경상북도 상주시 함창읍 나한리
700 번째 경상북도 문경시 마성면 남호리
701 번째 충청북도 괴산군 연풍면 행촌리
702 번째 충청북도 괴산군 장연면 조곡리
703 번째 충청북도 충주시 대소원면 완오리
704 번째 충청북도 충주시 중앙탑면 하구암리
705 번째 충청북도 충주시 노은면 신효리
706 번째 충청북도 충주시 노은면 문성리
707 번째 충청북도 음성군 감곡면 상우리
708 번째 경기도 여주시 가남읍 본두리
709 번째 경기도 여주시 세종대왕면 오계리
710 번째 경기도 여주시 세종대왕면 번도리
711 번째 경기도 여주시 흥천면 문장리
712 번째 경기도 양평군 강상면 병산리
713 번째 인천광역시 남동구 도림동
714 번째 경기도 시흥시 거모동
715 번째 경기도 시흥시 군자동
716 번째 경기도 안산시 단원구 선부동
717 번째 경기도 안산시 상록구 양상동
718 번째 경기도 안산시 상록구 장하동
719 번째 경기도 군포시 둔대동
720 번째 경기도 군포시 부곡동
721 번째 경기도 의왕시 삼동
722 번째 경기도 수원시 장안구 파장동
723 번째 경기도 수원시 영통구 이의동
724 번째 경기도 용인시 기흥구 신갈동
725 번째 경기도 용인시 처인구 포곡읍 마성리
726 번째 경기도 용인시 처인구 유방동
727 번째 경기도 용인시 처인구 양지면 양지리
728 번째 경기도 이천시 마장면 덕평리
729 번째 경기도 이천시 호법면 안평리
730 번째 경기도 이천시 대월면 사동리
731 번째 경기도 여주시 상거동
732 번째 경기도 여주시 멱곡동
733 번째 강원도 원주시 문막읍 동화리
734 번째 강원도 원주시 호저면 만종리
735 번째 강원도 원주시 가현동
736 번째 강원도 원주시 태장동
737 번째 강원도 횡성군 우천면 오원리
738 번째 강원도 횡성군 둔내면 우용리
739 번째 강원도 횡성군 둔내면 삽교리
740 번째 강원도 평창군 봉평면 면온리
741 번째 강원도 평창군 용평면 용전리
742 번째 강원도 평창군 용평면 속사리
743 번째 강원도 평창군 진부면 상진부리
744 번째 강원도 평창군 대관령면 횡계리
745 번째 인천광역시 남동구 도림동
746 번째 경기도 시흥시 거모동
747 번째 경기도 시흥시 군자동
748 번째 경기도 안산시 단원구 선부동
749 번째 경기도 안산시 상록구 양상동
750 번째 경기도 안산시 상록구 장하동
751 번째 경기도 군포시 둔대동
752 번째 경기도 군포시 부곡동
753 번째 경기도 의왕시 삼동
754 번째 경기도 수원시 장안구 파장동
755 번째 경기도 수원시 영통구 이의동
756 번째 경기도 용인시 기흥구 신갈동
757 번째 경기도 용인시 처인구 포곡읍 마성리
758 번째 경기도 용인시 처인구 유방동
759 번째 경기도 용인시 처인구 양지면 양지리
760 번째 경기도 이천시 마장면 덕평리
761 번째 경기도 이천시 호법면 안평리
762 번째 경기도 이천시 대월면 사동리
763 번째 경기도 여주시 상거동
764 번째 경기도 여주시 멱곡동
765 번째 강원도 원주시 문막읍 동화리
766 번째 강원도 원주시 호저면 만종리
767 번째 강원도 원주시 가현동
768 번째 강원도 원주시 태장동
769 번째 강원도 횡성군 우천면 오원리
770 번째 강원도 횡성군 둔내면 우용리
771 번째 강원도 횡성군 둔내면 삽교리
772 번째 강원도 평창군 봉평면 면온리
773 번째 강원도 평창군 용평면 용전리
774 번째 강원도 평창군 용평면 속사리
775 번째 강원도 평창군 진부면 상진부리
776 번째 강원도 평창군 대관령면 횡계리
777 번째 경상남도 김해시 대동면 초정리
778 번째 경상남도 김해시 대동면 괴정리
779 번째 경상남도 김해시 대동면 덕산리
780 번째 대구광역시 북구 금호동
781 번째 대구광역시 북구 관음동
782 번째 경상북도 칠곡군 가산면 다부리
783 번째 경상북도 칠곡군 가산면 천평리
784 번째 경상북도 군위군 군위읍 수서리
785 번째 경상북도 군위군 군위읍 수서리
786 번째 경상북도 의성군 봉양면 도원리
787 번째 경상북도 안동시 일직면 용각리
788 번째 경상북도 안동시 일직면 국곡리
789 번째 경상북도 안동시 풍산읍 노리
790 번째 경상북도 예천군 보문면 수계리
791 번째 경상북도 영주시 장수면 화기리
792 번째 경상북도 영주시 봉현면 오현리
793 번째 충청북도 단양군 대강면 두음리
794 번째 충청북도 단양군 적성면 소야리
795 번째 충청북도 제천시 금성면 월림리
796 번째 충청북도 제천시 금성면 월림리
797 번째 충청북도 제천시 봉양읍 봉양리
798 번째 강원도 원주시 신림면 신림리
799 번째 강원도 원주시 무실동
800 번째 강원도 원주시 지정면 신평리
801 번째 강원도 원주시 지정면 신평리
802 번째 강원도 원주시 호저면 옥산리
803 번째 강원도 횡성군 공근면 오산리
804 번째 강원도 홍천군 북방면 하화계리
805 번째 강원도 춘천시 동산면 조양리
806 번째 경상남도 김해시 대동면 초정리
807 번째 경상남도 김해시 대동면 괴정리
808 번째 경상남도 김해시 대동면 덕산리
809 번째 대구광역시 북구 금호동
810 번째 대구광역시 북구 관음동
811 번째 경상북도 칠곡군 가산면 다부리
812 번째 경상북도 칠곡군 가산면 천평리
813 번째 경상북도 군위군 군위읍 수서리
814 번째 경상북도 군위군 군위읍 수서리
815 번째 경상북도 의성군 봉양면 도원리
816 번째 경상북도 안동시 일직면 용각리
817 번째 경상북도 안동시 일직면 국곡리
818 번째 경상북도 안동시 풍산읍 노리
819 번째 경상북도 예천군 보문면 수계리
820 번째 경상북도 영주시 장수면 화기리
821 번째 경상북도 영주시 봉현면 오현리
822 번째 충청북도 단양군 대강면 두음리
823 번째 충청북도 단양군 적성면 소야리
824 번째 충청북도 제천시 금성면 월림리
825 번째 충청북도 제천시 금성면 월림리
826 번째 충청북도 제천시 봉양읍 봉양리
827 번째 강원도 원주시 신림면 신림리
828 번째 강원도 원주시 무실동
829 번째 강원도 원주시 지정면 신평리
830 번째 강원도 원주시 지정면 신평리
831 번째 강원도 원주시 호저면 옥산리
832 번째 강원도 횡성군 공근면 오산리
833 번째 강원도 홍천군 북방면 하화계리
834 번째 강원도 춘천시 동산면 조양리
835 번째 경기도 하남시 선동
836 번째 경기도 하남시 선동
837 번째 경기도 남양주시 와부읍 덕소리
838 번째 경기도 남양주시 와부읍 월문리
839 번째 경기도 남양주시 화도읍 창현리
840 번째 경기도 양평군 서종면 수입리
841 번째 경기도 가평군 설악면 신천리
842 번째 강원도 춘천시 남면 발산리
843 번째 강원도 춘천시 동산면 군자리
844 번째 강원도 춘천시 동산면 군자리
845 번째 강원도 춘천시 동산면 조양리
846 번째 강원도 홍천군 화촌면 외삼포리
847 번째 강원도 홍천군 내촌면 물걸리
848 번째 강원도 인제군 상남면 하남리
849 번째 강원도 인제군 기린면 진동리
850 번째 강원도 양양군 서면 영덕리
851 번째 경기도 하남시 선동
852 번째 경기도 하남시 선동
853 번째 경기도 남양주시 와부읍 덕소리
854 번째 경기도 남양주시 와부읍 월문리
855 번째 경기도 남양주시 화도읍 창현리
856 번째 경기도 양평군 서종면 수입리
857 번째 경기도 가평군 설악면 신천리
858 번째 강원도 춘천시 남면 발산리
859 번째 강원도 춘천시 동산면 군자리
860 번째 강원도 춘천시 동산면 군자리
861 번째 강원도 춘천시 동산면 조양리
862 번째 강원도 홍천군 화촌면 외삼포리
863 번째 강원도 홍천군 내촌면 물걸리

In [23]:
df['행정동 주소'] = binlist

In [25]:
df.to_excel('행정동 추가.xlsx')